# Generated by Django 4.2.10 on 2024-03-02 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('id',), 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
    ]
